name = "teakit"
author = "Stefan Olivier"
email = "s.olivier1194@gmail.com"
url = "https://github.com/slothsh/teakit"
description = "A quaint little build library suitable for a Sunday tea-break"

[version]
major = 0
minor = 0
sub = 0
